<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ROBOT DIMENSIONS (measured Feb 2026, all values in meters) -->
    <xacro:property name="base_length" value="0.7112" />      <!-- 28 inches -->
    <xacro:property name="base_width"  value="0.508"  />      <!-- 20 inches -->
    <xacro:property name="base_height" value="0.1524" />      <!-- 6 inches  -->
    <xacro:property name="base_mass"   value="6.8"    />      <!-- ~15 lbs estimate -->

    <!-- Wheel dimensions (5 in radius including treads+rims, 3.5 in thick) -->
    <xacro:property name="wheel_radius" value="0.127"  />     <!-- 5 inches  -->
    <xacro:property name="wheel_length" value="0.0889" />     <!-- 3.5 inches -->
    <xacro:property name="wheel_mass"   value="0.5"    />

    <!-- Track widths: center-of-left-wheel to center-of-right-wheel -->
    <xacro:property name="wheel_separation"      value="0.762"  />  <!-- 30 in — front + mid axles -->
    <xacro:property name="rear_wheel_separation" value="0.9144" />  <!-- 36 in — rear axle (wider) -->

    <!-- Axle X positions (mid axle = chassis center; 18 in = 0.4572 m between each pair) -->
    <xacro:property name="front_axle_x" value="0.2286"  />    <!-- +9 inches from center -->
    <xacro:property name="mid_axle_x"   value="0.0"     />
    <xacro:property name="rear_axle_x"  value="-0.2286" />    <!-- -9 inches from center -->

    <!-- LIDAR pole: height from chassis top surface to LIDAR center -->
    <xacro:property name="lidar_pole_height" value="0.508" />  <!-- 20 inches -->

    <!-- Antenna heights measured from chassis bottom (two different antennas) -->
    <xacro:property name="left_antenna_height"  value="0.762"  />  <!-- 2.4 GHz — 30 inches, left rear -->
    <xacro:property name="right_antenna_height" value="0.9144" />  <!-- 900 MHz  — 36 inches, right rear -->

    <!-- BASE FOOTPRINT -->
    <link name="base_footprint" />

    <!-- BASE LINK -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <inertia ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}"
                     ixy="0" ixz="0"
                     iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}"
                     iyz="0"
                     izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}" />
        </inertial>
    </link>

    <!-- WHEEL MACRO -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}"
                         ixy="0" ixz="0"
                         iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}"
                         iyz="0"
                         izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}" />
            </inertial>
        </link>
    </xacro:macro>

    <!-- 6 WHEELS -->
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="mid_left" />
    <xacro:wheel_link prefix="mid_right" />
    <xacro:wheel_link prefix="rear_left" />
    <xacro:wheel_link prefix="rear_right" />

    <!-- IMU LINK (ZED2i internal IMU) -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.01" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green">
                <color rgba="0 1 0 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- ZED2i CAMERA LINK -->
    <link name="zed_camera_link">
        <visual>
            <geometry>
                <box size="0.033 0.175 0.030" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="dark_grey">
                <color rgba="0.2 0.2 0.2 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.033 0.175 0.030" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.175" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- LIDAR POLE (visual only, for collision awareness) -->
    <link name="lidar_pole_link">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="${lidar_pole_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="${lidar_pole_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- LIDAR LINK (STL-19P) - on top of the pole -->
    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.035" length="0.045" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="dark_grey">
                <color rgba="0.2 0.2 0.2 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.035" length="0.045" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- ANTENNA STICKS (rear of chassis, visual/collision only) -->
    <!-- Left = 2.4 GHz (30 in), Right = 900 MHz (36 in) — different heights -->
    <xacro:macro name="antenna_link" params="prefix height">
        <link name="${prefix}_antenna_link">
            <visual>
                <geometry>
                    <cylinder radius="0.005" length="${height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.005" length="${height}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="0.05" />
                <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:antenna_link prefix="left"  height="${left_antenna_height}"  />
    <xacro:antenna_link prefix="right" height="${right_antenna_height}" />

    <!-- ==================== JOINTS ==================== -->

    <!-- Base footprint to base link -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- WHEEL JOINT MACRO (takes per-axle separation) -->
    <xacro:macro name="wheel_joint" params="prefix x_pos y_offset">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <origin xyz="${x_pos} ${y_offset} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <!-- Front axle (standard width) -->
    <xacro:wheel_joint prefix="front_left" x_pos="${front_axle_x}" y_offset="${wheel_separation / 2.0}" />
    <xacro:wheel_joint prefix="front_right" x_pos="${front_axle_x}" y_offset="${-wheel_separation / 2.0}" />

    <!-- Middle axle (standard width) -->
    <xacro:wheel_joint prefix="mid_left" x_pos="${mid_axle_x}" y_offset="${wheel_separation / 2.0}" />
    <xacro:wheel_joint prefix="mid_right" x_pos="${mid_axle_x}" y_offset="${-wheel_separation / 2.0}" />

    <!-- Rear axle (wider) -->
    <xacro:wheel_joint prefix="rear_left" x_pos="${rear_axle_x}" y_offset="${rear_wheel_separation / 2.0}" />
    <xacro:wheel_joint prefix="rear_right" x_pos="${rear_axle_x}" y_offset="${-rear_wheel_separation / 2.0}" />

    <!-- IMU centered on top of chassis -->
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 ${base_height + 0.005}" rpy="0 0 0" />
    </joint>

    <!-- ZED2i: embedded in center of front panel, 3 in (0.0762 m) above chassis bottom -->
    <joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="zed_camera_link" />
        <origin xyz="${base_length / 2.0} 0 0.0762" rpy="0 0 0" />
    </joint>

    <!-- LIDAR pole mounted center of chassis -->
    <joint name="lidar_pole_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_pole_link" />
        <origin xyz="0 0 ${base_height + lidar_pole_height / 2.0}" rpy="0 0 0" />
    </joint>

    <!-- LIDAR on top of pole -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="laser_frame" />
        <origin xyz="0 0 ${base_height + lidar_pole_height + 0.023}" rpy="0 0 0" />
    </joint>

    <!-- 2.4 GHz antenna: left side of back face, base at chassis bottom, rising upward -->
    <joint name="left_antenna_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_antenna_link" />
        <origin xyz="${-base_length / 2.0} ${base_width / 2.0} ${left_antenna_height / 2.0}" rpy="0 0 0" />
    </joint>

    <!-- 900 MHz antenna: right side of back face, base at chassis bottom, rising upward -->
    <joint name="right_antenna_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_antenna_link" />
        <origin xyz="${-base_length / 2.0} ${-base_width / 2.0} ${right_antenna_height / 2.0}" rpy="0 0 0" />
    </joint>

</robot>
