scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: front_180_only
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.5708   # -90° (rover's right)
        upper_angle:  1.5708   # +90° (rover's left)
